CREATE DATABASE IF NOT EXISTS tvm;

USE tvm;

CREATE TABLE IF NOT EXISTS advisory_texts (
    id INT AUTO_INCREMENT,
    category VARCHAR(255) NOT NULL,
    sub_category VARCHAR(255) NOT NULL,
    text TEXT NOT NULL,
    PRIMARY KEY (id)
);