rewrite_task_minrisk:
  description: >
    Stel de tekst op door informatie uit de input te gebruiken in de ondergenoemde standaard tekst. De informatie die ingevuld moet worden staat tussen de blokhaken. Probeer alle benodigde data uit de input te halen en de blokhaken te vervangen met de data.
    
    Je dient deze parameters te integreren in de volgende standaardtekst: 'Tijdens de inventarisatie hebben wij vastgesteld dat u alle risico's tot een minimum wenst te beperken. Mijn advies is om alle trekkers + opleggers WA volledig casco te verzekeren. Voor het verzekerde bedrag, gebaseerd op € (basis_verzekerd_bedrag) en het eigen risico van € (eigen_risico). Deze bedragen vindt u terug op de polis. U geeft aan dat u (invulling op basis van advies_opgevolgd en reden_niet_opvolgen).'

    Indien het advies wordt opgevolgd, vul je in: 'mijn advies opvolgt.'
    Indien het advies niet wordt opgevolgd, vul je in: 'niet mijn advies opvolgt, omdat u (reden_niet_opvolgen).' en voeg je direct de volgende waarschuwingsclausule toe: 'Wij willen u erop wijzen dat het accepteren van dit risico mogelijke gevolgen kan hebben voor uw financiële reserves. In het ergste geval zou uw bedrijfscontinuïteit in gevaar kunnen komen. U bent zich hiervan bewust en accepteert deze risico's.'

    Het eindresultaat moet één coherente, grammaticaal correcte Nederlandse alinea zijn.
  expected_output: >
    De verwachte output is een volledig samengestelde alinea in het Nederlands, die de verzamelde data correct verwerkt en de conditionele logica toepast.
  agent: writer


rewrite_task_risk_in_euros_damage_to_third_parties:
  description: >
    Deze tekst wordt altijd gebruikt wanneer de klant wenst geadviseerd te worden op basis van de risicobereidheid in euro's en het gaat om schade aan derden of schade door eigen toedoen. Stel de tekst op door informatie uit de input te gebruiken in de ondergenoemde standaard tekst, de informatie dat ingevuld moet worden staat tussen de haken. Probeer alle benodigde data uit de input the halen en de haken te vervangen met de data.
    
    Je dient deze parameters te integreren in de volgende standaardtekst: 'Tijdens de inventarisatie hebben wij vastgesteld dat u risico's tot een bedrag van (limiet_in_euros) wilt en kunt dragen. Mijn advies is om (onderdelen_te_verzekeren) te verzekeren. Voor het verzekerde bedrag, gebaseerd op € (basis_verzekerd_bedrag) en het eigen risico van € (eigen_risico)/standaard eigen risico. Deze bedragen vindt u terug op de polis. U geeft aan dat u (volgt_advies_op)'
    
    Als (volgt_advies_op) waar is, vul je in: 'mijn advies opvolgt.'
    Als (volgt_advies_op) niet waar is, vul je in: 'niet mijn advies opvolgt, omdat u (reden_niet_opvolgen). Wij willen u erop wijzen dat het accepteren van dit risico mogelijke gevolgen kan hebben voor uw financiële reserves. In het ergste geval zou uw bedrijfscontinuïteit in gevaar kunnen komen. U bent zich hiervan bewust en accepteert deze risico's.'.
    
    Het eindresultaat moet één coherente, grammaticaal correcte Nederlandse alinea zijn.
  expected_output: >
    De verwachte output is een volledig samengestelde alinea in het Nederlands, die de verzamelde data correct verwerkt en de conditionele logica toepast.
  agent: writer


rewrite_task_risk_in_euros_damage_by_standstill:
  description: >
    Deze tekst wordt altijd gebruikt wanneer de klant wenst geadviseerd te worden op basis van de risicobereidheid in euro's en het gaat om schade door stilstand. Stel de tekst op door informatie uit de input te gebruiken in de ondergenoemde standaard tekst, de informatie dat ingevuld moet worden staat tussen de haken. Probeer alle benodigde data uit de input the halen en de haken te vervangen met de data.
    
    Je dient deze parameters te integreren in de volgende standaardtekst: 'Tijdens de inventarisatie hebben wij vastgesteld dat u risico's tot een bedrag van 10.000 wilt en kunt dragen. Mijn advies is om (sluit_bedrijfskosten_dekking_af). Voor het verzekerde bedrag, gebaseerd op € (basis_verzekerd_bedrag) en het eigen risico van € (eigen_risico)/standaard eigen risico. Deze bedragen vindt u terug op de polis. U geeft aan dat u (volgt_advies_op)'
    
    Als (sluit_bedrijfskosten_dekking_af) waar is, vul je in 'een extra bedrijfskosten dekking af te sluiten.'
    Als (sluit_bedrijfskosten_dekking_af) niet waar is, vul je in 'geen extra bedrijfskosten dekking af te sluiten.'
    
    Als (volgt_advies_op) waar is, vul je in: 'mijn advies opvolgt.'
    Als (volgt_advies_op) niet waar is, vul je in: 'niet mijn advies opvolgt, omdat u (reden_niet_opvolgen). Wij willen u erop wijzen dat het accepteren van dit risico mogelijke gevolgen kan hebben voor uw financiële reserves. In het ergste geval zou uw bedrijfscontinuïteit in gevaar kunnen komen. U bent zich hiervan bewust en accepteert deze risico's.'.
    
    Het eindresultaat moet één coherente, grammaticaal correcte Nederlandse alinea zijn.
  expected_output: >
    De verwachte output is een volledig samengestelde alinea in het Nederlands, die de verzamelde data correct verwerkt en de conditionele logica toepast.
  agent: writer


rewrite_task_risk_in_euros_loss_of_personal_items:
  description: >
    Deze tekst wordt altijd gebruikt wanneer de klant wenst geadviseerd te worden op basis van de risicobereidheid in euro's en het gaat om verlies van persoonlijke goederen van de chauffeur. Stel de tekst op door informatie uit de input te gebruiken in de ondergenoemde standaard tekst, de informatie dat ingevuld moet worden staat tussen de haken. Probeer alle benodigde data uit de input the halen en de haken te vervangen met de data.
    
    Je dient deze parameters te integreren in de volgende standaardtekst: 'Tijdens de inventarisatie hebben wij vastgesteld dat u risico's tot een bedrag van 10.000 wilt en kunt dragen. Mijn advies is om (sluit_diefstal_bagage_dekking_af). Voor het verzekerde bedrag en het eigen risico verwijs ik u naar de polis. U geeft aan dat u (volgt_advies_op)'
    
    Als (sluit_diefstal_bagage_dekking_af) waar is, vul je in 'een diefstal bagage dekking af te sluiten.'
    Als (sluit_diefstal_bagage_dekking_af) niet waar is, vul je in 'geen diefstal bagage dekking af te sluiten.'
    
    Als (volgt_advies_op) waar is, vul je in: 'mijn advies opvolgt.'
    Als (volgt_advies_op) niet waar is, vul je in: 'niet mijn advies opvolgt, omdat u (reden_niet_opvolgen). Wij willen u erop wijzen dat het accepteren van dit risico mogelijke gevolgen kan hebben voor uw financiële reserves. In het ergste geval zou uw bedrijfscontinuïteit in gevaar kunnen komen. U bent zich hiervan bewust en accepteert deze risico's.'.
    
    Het eindresultaat moet één coherente, grammaticaal correcte Nederlandse alinea zijn.
  expected_output: >
    De verwachte output is een volledig samengestelde alinea in het Nederlands, die de verzamelde data correct verwerkt en de conditionele logica toepast.
  agent: writer


rewrite_task_risk_in_euros_damage_to_passengers:
  description: >
    Deze tekst wordt altijd gebruikt wanneer de klant wenst geadviseerd te worden op basis van de risicobereidheid in euro's en het gaat om (letsel)schade passagiers. Stel de tekst op door informatie uit de input te gebruiken in de ondergenoemde standaard tekst, de informatie dat ingevuld moet worden staat tussen de haken. Probeer alle benodigde data uit de input the halen en de haken te vervangen met de data.
    
    Je dient deze parameters te integreren in de volgende standaardtekst: 'Tijdens de inventarisatie hebben wij vastgesteld dat u risico's tot een bedrag van 10.000 wilt en kunt dragen. Mijn advies is om (sluit_SVI_dekking_af). Voor het verzekerde bedrag en het eigen risico verwijs ik u naar de polis. U geeft aan dat u (volgt_advies_op)'
    
    Als (sluit_SVI_dekking_af) waar is, vul je in 'een SVI dekking af te sluiten.'
    Als (sluit_SVI_dekking_af) niet waar is, vul je in 'geen SVI dekking af te sluiten.'
    
    Als (volgt_advies_op) waar is, vul je in: 'mijn advies opvolgt.'
    Als (volgt_advies_op) niet waar is, vul je in: 'niet mijn advies opvolgt, omdat u (reden_niet_opvolgen). Wij willen u erop wijzen dat het accepteren van dit risico mogelijke gevolgen kan hebben voor uw financiële reserves. In het ergste geval zou uw bedrijfscontinuïteit in gevaar kunnen komen. U bent zich hiervan bewust en accepteert deze risico's.'.
    
    Het eindresultaat moet één coherente, grammaticaal correcte Nederlandse alinea zijn.
  expected_output: >
    De verwachte output is een volledig samengestelde alinea in het Nederlands, die de verzamelde data correct verwerkt en de conditionele logica toepast.
  agent: writer


rewrite_task_deviate_from_identification_damage_to_third_parties:
  description: >
    Deze tekst wordt gebruikt wanneer de klant aangeeft bereid te zijn meer risico te dragen dan tijdens de inventarisatie is vastgesteld en het gaat om schade aan derden of schade door eigen toedoen. Stel de tekst op door informatie uit de input te verwerken in de onderstaande standaardtekst. De gegevens die ingevuld moeten worden staan tussen de haken. Probeer alle benodigde data uit de input te halen en de haken te vervangen met de juiste data.
    
    Je dient deze parameters te integreren in de volgende standaardtekst: 'U geeft aan dat u op dit onderdeel bereid bent meer risico te lopen dan wij samen hebben vastgesteld tijdens de inventarisatie. U geeft aan dat uw risicobereidheid op dit onderdeel (risicobereidheid_omschrijving) is. U geeft aan dat u dit kunt en wilt dragen. Mijn advies is om (onderdelen_te_verzekeren) te verzekeren. Voor het verzekerde bedrag, gebaseerd op € (basis_verzekerd_bedrag) en het eigen risico van € (eigen_risico/standaard eigen risico). Deze bedragen vindt u terug op de polis. U geeft aan dat u (volgt_advies_op)'
    
    Als (volgt_advies_op) waar is, vul je in: 'mijn advies opvolgt.'
    Als (volgt_advies_op) niet waar is, vul je in: 'niet mijn advies opvolgt, omdat u (reden_niet_opvolgen). Wij willen u erop wijzen dat het accepteren van dit risico mogelijke gevolgen kan hebben voor uw financiële reserves. In het ergste geval zou uw bedrijfscontinuïteit in gevaar kunnen komen. U bent zich hiervan bewust en accepteert deze risico's.'.
    
    Het eindresultaat moet één coherente, grammaticaal correcte Nederlandse alinea zijn.
  expected_output: >
    De verwachte output is een volledig samengestelde alinea in het Nederlands, die de verzamelde data correct verwerkt en de conditionele logica toepast.
  agent: writer


rewrite_task_identify_by_risk_damage_to_third_parties:
  description: >
    Deze tekst wordt gebruikt wanneer de klant per risico in kaart wil brengen hoeveel de klant wil en kan dragen en het gaat om schade aan derden of schade door eigen toedoen. Stel de tekst op door informatie uit de input te verwerken in de onderstaande standaardtekst. De gegevens die ingevuld moeten worden staan tussen de haken. Probeer alle benodigde data uit de input te halen en de haken te vervangen met de juiste data.
    
    Je dient deze parameters te integreren in de volgende standaardtekst: 'Tijdens de inventarisatie hebben wij vastgesteld dat wij per risico in kaart brengen hoeveel risico u wilt en kunt dragen. U heeft aangegeven dat uw verzekeringsbeleid is om (omschrijving_verzekeringsbeleid). U geeft aan dat u dit kunt en wilt dragen. Mijn advies is om (onderdelen_te_verzekeren) te verzekeren. Voor het verzekerde bedrag, gebaseerd op € (basis_verzekerd_bedrag) en het eigen risico van € (eigen_risico/standaard eigen risico). Deze bedragen vindt u terug op de polis. U geeft aan dat u (volgt_advies_op)'
    
    Als (volgt_advies_op) waar is, vul je in: 'mijn advies opvolgt.'
    Als (volgt_advies_op) niet waar is, vul je in: 'niet mijn advies opvolgt, omdat u (reden_niet_opvolgen). Wij willen u erop wijzen dat het accepteren van dit risico mogelijke gevolgen kan hebben voor uw financiële reserves. In het ergste geval zou uw bedrijfscontinuïteit in gevaar kunnen komen. U bent zich hiervan bewust en accepteert deze risico's.'.
    
    Het eindresultaat moet één coherente, grammaticaal correcte Nederlandse alinea zijn.
  expected_output: >
    De verwachte output is een volledig samengestelde alinea in het Nederlands, die de verzamelde data correct verwerkt en de conditionele logica toepast.
  agent: writer


research:
  description: >
    Lees de gehele input. Haal hier alle benodigde data voor de writer uit. Kijk naar {input}
  expected_output: >
    Eigen risico
    Verzekerd bedrag
    Advies wordt opgevolgd
    Reden dat advies niet wordt opgevolgd indien van toepassing
  agent: reader
