retrieve_template:
  description: >
    Op basis van het uitgevoerde onderzoek, haal de juiste template op uit de database en vul dit in.
  expected_output: >
    Geef een ingevuld template terug zonder gaten.
  agent: writer

research:
  description: >
    Lees de gehele input. Haal hier alle benodigde data voor de writer uit. Kijk naar {input}
  expected_output: >
    Inventaris
    Welk soort advies
    Eigen risico
    Verzekerd bedrag
    Advies wordt opgevolgd
    Reden dat advies niet wordt opgevolgd indien van toepassing
    Overige context
  agent: reader

fetch_template_from_db:
  description: >
    Retrieve the actual advisory text template from the database.
    
    CRITICAL: Return the TEXT CONTENT, not SQL statements.
    
    Steps:
    1. Use the category and subcategory identified in previous task
    2. Query the database for matching advisory text
    3. Return the complete text from the 'text' column
    
    Do not return SQL queries - return the actual advisory text content.
  expected_output: >
    The complete Dutch advisory text template from the database.
