name: Run Pytest

on:
  push:
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: test_password
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install uv
      run: pip install uv

    - name: Install dependencies
      run: |
        cd tvm
        uv sync --dev

    - name: Wait for MySQL to be ready
      run: |
        for i in {1..30}; do
          if mysqladmin ping -h "127.0.0.1" -P 3306 -u root -p test_password --silent; then
            echo "MySQL is ready!"
            break
          fi
          echo "Waiting for MySQL..."
          sleep 2
        done

    - name: Create .env file
      run: |
        cat << EOF > .env
        SQL_CONNECTION=mysql+pymysql://test_user:test_password@127.0.0.1:3306/test_db
        SECRET=QWERTYUIOPASDFGHJKLZXCVBNM
        ORIGINS_CALL=*
        EOF

    - name: Run tests
      run: |
        cd tvm/src/tvm
        pytest